[package]
name = "ani-crab"
version = "0.1.0"
edition = "2021"

[dependencies]
form_urlencoded = "1.2.1"
fuzzypicker = "0.2.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
